---

- name: restart docker
  service:
    name: docker
    state: restarted

- name: clean yum cache
  command: /usr/bin/yum clean all
  args:
    warn: false

- name: refresh docker host info
  community.docker.docker_host_info:
  check_mode: no
  changed_when: false
  register: docker_info
  tags:
    - skip_ansible_lint  # Suppressing the linter

- name: reload firewalld
  raw: firewall-cmd --reload
  check_mode: no
  changed_when: false
  listen: reload firewalld